apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: hadoop
  labels:
    app: hadoop
    name: hadoop-master-svc
    tier: backend
spec:
  clusterIp: None
  type: LoadBalancer
  ports:
    # namenode
    - name: p1
      port: 50070
    - name: p2
      port: 50470
    - name: p3
      port: 8020
    # journalnode
    - name: p4
      port: 8485
    - name: p5
      port: 8480
    # yarn
    - name: p6
      port: 8030
    - name: p7
      port: 8031
    - name: p8
      port: 8088
    - name: p9
      port: 8033
    - name: p10
      port: 10020
    - name: p11
      port: 19888
    # hbase
    - name: p12
      port: 60000
    - name: p13
      port: 16010
    - name: p14
      port: 16020
    - name: p15
      port: 16030
    - name: p16
      port: 2181
    - name: p17
      port: 2888
    - name: p18
      port: 3888
    # other
    - name: p19
      port: 22
    - name: p20
      port: 9000
      targetPort: 9000
    - name: p24
      port: 9001
    # spark
    - name: p21                                                                                                      
      port: 18080
    - name: p22                                                                                                     
      port: 7077
    # SecondaryNameNode
    - name: p23                                                                                                      
      port: 50090
     
  externalIPs:
    - 10.37.149.96
  selector:
    app: hadoop
    name: hadoop-master-rc
    tier: backend
